export const phonemeLetterMap = {
  // Consonants
  b: ["b", "bb"],
  d: ["d", "dd", "ed"],
  f: ["f", "ff", "ph", "gh", "lf", "ft"],
  g: ["g", "gg", "gh", "gu", "gue"],
  h: ["h", "wh"],
  dʒ: ["j", "ge", "g", "dge", "di", "gg"],
  k: ["k", "c", "ch", "cc", "lk", "qu", "q(u)", "ck", "x"],
  l: ["l", "ll"],
  m: ["m", "mm", "mb", "mn", "lm"],
  n: ["n", "nn", "kn", "gn", "pn", "mn"],
  p: ["p", "pp"],
  r: ["r", "rr", "wr", "rh"],
  s: ["s", "ss", "c", "sc", "ps", "st", "ce", "se"],
  t: ["t", "tt", "th", "ed"],
  v: ["v", "f", "ph", "ve"],
  w: ["w", "wh", "u", "o"],
  z: ["z", "zz", "s", "ss", "x", "ze", "se"],
  ʒ: ["s", "si", "z"],
  tʃ: ["ch", "tch", "tu", "te"],
  ʃ: ["sh", "ce", "s", "ci", "si", "ch", "sci", "ti"],
  θ: ["th"],
  ð: ["th"],
  ŋ: ["ng", "n", "ngue"],
  j: ["y", "i", "j"],

  // Vowels
  æ: ["a", "ai", "au"],
  eɪ: [
    "a",
    "ai",
    "eigh",
    "aigh",
    "ay",
    "er",
    "et",
    "ei",
    "au",
    "a_e",
    "ea",
    "ey",
  ],
  ɛ: ["e", "ea", "u", "ie", "ai", "a", "eo", "ei", "ae"],
  "i:": ["e", "ee", "ea", "y", "ey", "oe", "ie", "i", "ei", "eo", "ay"],
  ɪ: ["i", "e", "o", "u", "ui", "y", "ie"],
  aɪ: ["i", "y", "igh", "ie", "uy", "ye", "ai", "is", "eigh", "i_e"],
  ɒ: ["a", "ho", "au", "aw", "ough"],
  oʊ: ["o", "oa", "o_e", "oe", "ow", "ough", "eau", "oo", "ew"],
  ʊ: ["o", "oo", "u", "ou"],
  ʌ: ["u", "o", "oo", "ou"],
  "u:": ["o", "oo", "ew", "ue", "u_e", "oe", "ough", "ui", "oew", "ou"],
  ɔɪ: ["oi", "oy", "uoy"],
  aʊ: ["ow", "ou", "ough"],
  ə: ["a", "er", "i", "ar", "our", "ur"],
  eəʳ: ["air", "are", "ear", "ere", "eir", "ayer"],
  "ɑ:": ["a"],
  "ɜ:ʳ": ["ir", "er", "ur", "ear", "or", "our", "yr"],
  "ɔ:": [
    "aw",
    "a",
    "or",
    "oor",
    "ore",
    "oar",
    "our",
    "augh",
    "ar",
    "ough",
    "au",
  ],
  ɪəʳ: ["ear", "eer", "ere", "ier"],
  ʊəʳ: ["ure", "our"],
};
